#! /bin/bash

#============================================================================================================
#           Twitter:      https://twitter.com/mahamdi.amine
#           Github :      https://github.com/MahamdiAmine
#           Website:      https://mahamdiamine.github.io/
#============================================================================================================
yellow='\e[1;33m'
green='\e[0;34m'
BlueF='\e[1;34m'
Red="\e[1;31m"
Cclear="\e[0m"
dir=`pwd`
BUS=/sys/bus/usb/drivers_autoprobe
arg=$1
clear
#######################################################################################
bar ()
{
	echo -n  Initialisation = =;
	sleep 3 & while [ "$(ps a | awk '{print $1}' | grep $!)" ] ; do for X in '-' '\' '|' '/'; do echo -en "\b$X"; sleep 0.1; done; done
  echo
	echo
BAR='█║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║█'

for i in {1..50}; do
    echo -ne "\r             ${BAR:0:$i}"
    sleep 0.04
done
}
################################# < Super User Check > ################################
if [ $EUID -ne 0 ]; then
	echo -e "${Red}You don't have admin privilegies, please execute the script as root.$Cclear"
	echo
	exit 1
fi
################################### < XTerm Checks > ###################################
if [ ! "${DISPLAY:-}" ]; then
    echo -e "${CRed}The script should be exected inside a X (graphical) session.$CClr"
		echo
		exit 2
fi
########################################################################################
if [ " $arg " = ' init ' ] ; then
echo
#echo -e $yellow"  [*] Initialisation ..."
echo -e $BlueF""
service network-manager stop;
macchanger -r wlan0 > /dev/null
macchanger -r eth0 > /dev/null
service network-manager start;
echo 0 > $BUS
echo
bar
echo
echo
echo -e $yellow"  [*] Done ."
sleep 1
echo
clear
elif
[ " $arg " = ' ghoston ' ] ; then
echo -e $yellow "   Becaming ghost in the net ..."
sudo	sh /home/mahamdi/LINUX/scripts/GhostInTheNet/GhostInTheNet.sh on wlan0 > /dev/null ;
  sh /home/mahamdi/LINUX/scripts/GhostInTheNet/GhostInTheNet.sh on eth0 > /dev/null;
echo -e $yellow"  [*] Done ."
sleep 1
elif
[ " $arg " = ' ghostoff ' ] ; then
echo -e $yellow "   turning off the mode  ghost in the net ..."
  sh /home/mahamdi/LINUX/scripts/GhostInTheNet/GhostInTheNet.sh off wlan0 ;
  sh /home/mahamdi/LINUX/scripts/GhostInTheNet/GhostInTheNet.sh off eth0 ;
echo -e $yellow"  [*] Done ."
sleep 1
elif
[ " $arg " = ' kick ' ] ; then
	clear
python3 /home/mahamdi/LINUX/scripts/kickthemout/kickthemout.py
elif
[ " $arg " = ' kill ' ] ; then
	echo -e $yellow "   starting wifijammer ... "
python /home/mahamdi/LINUX/scripts/wifijammer/wifijammer.py
sleep 1
elif
[ " $arg " = ' chess ' ] ; then
 cd /home/mahamdi/lila/
 systemctl start nginx.service
 systemctl start mongodb.service
 echo -e $yellow"  [*] Done ."
 sh ./bin/dev run  > /dev/null &
 google-chrome l.org > /dev/null &
	sleep 1
	cd dir
elif
[ " $arg " = ' open ' ] ; then
	nautilus --browser $path
elif
[ " $arg " = ' fix ' ] ; then
	echo -e $yellow "Are you sure ? remember last time "
	  rm /var/lib/dpkg/lock
	  dpkg --configure -a
	  rm /var/lib/apt/lists/lock
	  rm /var/cache/apt/archives/lock
 elif
 [ " $arg " = ' update ' ] ; then
 apt-get -y update && apt-get -y upgrade && apt-get -y dist-upgrade
elif
[ " $arg " = ' piano ' ] ; then
cd /home/mahamdi/piano-rs/
cargo build --release > /dev/null &
./target/release/piano-rs > /dev/null &
cd dir
elif
[ " $arg " = ' jmerise ' ] ; then
java -jar /opt/JMerise/JMerise.jar > /dev/null &
elif
[ " $arg " = ' packet ' ] ; then
cd /opt/PacketTrace/bin/
./PacketTracer7 > /dev/null &
cd dir
elif
[ " $arg " = ' anonyme ' ] ; then
	python /home/mahamdi/LINUX/scripts/anonymeMail.py
elif
[ " $arg " = ' temp ' ] ; then
	watch sensors ;
elif
[ " $arg " = ' inlightme ' ] ; then
	sudo echo 1 > /sys/devices/platform/sony-laptop/kbd_backlight ;
elif
[ " $arg " = ' darkme ' ] ; then
	sudo echo -1 > /sys/devices/platform/sony-laptop/kbd_backlight ;
elif
[ " $arg " = ' usb ' ] ; then
echo
echo -e $yellow '!!! USB OPENED FOR 10 SECONDS !!!'
echo 1 > $BUS
sleep 20
echo 1 > $BUS
clear
echo
echo -e $Red '!!! USB BLOCKED !!!'
echo
elif
[ " $arg " = ' proxyon ' ] ; then
cat << "EOF" > /etc/apt/apt.conf
Acquire::http::proxy "http://10.0.0.3:80/";
Acquire::ftp::proxy "ftp:http://10.0.0.3:80/";
Acquire::https::proxy "http://10.0.0.3:80/";
EOF
elif
[ " $arg " = ' proxyoff ' ] ; then
cat << "EOF" > /etc/apt/apt.conf
EOF
elif [ " $arg " = ' -h ' ] || [ " $arg " = ' --help ' ]; then
		echo ""
		echo "[option]"
		echo ""
		echo " init = Initialisation "
		echo ""
		echo " ghost on  "
		echo ""
		echo " ghost off "
		echo ""
		echo " kick = kickthemout"
		echo ""
		echo " kill = wifijammer "
		echo ""
		echo " chess = start lichess in localhost "
		echo ""
		echo " open "
		echo ""
		echo " fix = Fix “Unable to lock the administration directory (/var/lib/dpkg/)“ "
		echo ""
		echo " update = update the system "
		echo ""
		echo " piano = open piano-rs "
		echo ""
		echo " jmerise "
		echo ""
		echo " packet :PacketTracer7 "
		echo ""
		echo " proxyon "
		echo ""
		echo " proxyoff "
		echo ""
		echo " anonyme :send an anonymous mail"
		echo ""
		echo " temp :watch the temp in C° "
		echo ""
		echo " -h = help "
		echo ""
	   else
		echo -e $green " use  frlm -h for help "
fi
